package com.acs_plugin


object Constants {

    object MethodChannels {
        const val SETUP_CHAT_SERVICE = "setupChatService"
        const val DISCONNECT_CHAT_SERVICE = "disconnectChatService"
        const val INIT_CHAT_THREAD = "initChatThread"
        const val GET_INITIAL_MESSAGES = "getInitialMessages"
        const val RETRIEVE_CHAT_THREAD_PROPERTIES = "retrieveChatThreadProperties"
        const val GET_LIST_OF_PARTICIPANTS = "getListOfParticipants"
        const val GET_PREVIOUS_MESSAGES = "getPreviousMessages"
        const val GET_LAST_MESSAGE = "getLastMessage"
        const val SEND_MESSAGE = "sendMessage"
        const val EDIT_MESSAGE = "editMessage"
        const val DELETE_MESSAGE = "deleteMessage"
        const val SEND_READ_RECEIPT = "sendReadReceipt"
        const val SEND_TYPING_INDICATOR = "sendTypingIndicator"
        const val IS_CHAT_HAS_MORE_MESSAGES = "isChatHasMoreMessages"
        const val GET_LIST_READ_RECEIPTS = "getListReadReceipts"
        const val GET_PRELOADED_ACTION = "getPreloadedAction"
        const val SET_USER_DATA = "setUserData"
        const val GET_TOKEN = "getToken"
        const val INITIALIZE_ROOM_CALL = "initializeRoomCall"
        const val GET_INITIAL_LIST_THREADS = "getInitialListThreads"
        const val IS_MORE_THREADS_AVAILABLE = "isMoreThreadsAvailable"
        const val GET_NEXT_THREADS = "getNextThreads"
    }

    object FlutterEvents {
        const val ON_SHOW_CHAT = "onShowChat"
        const val ON_USER_CALL_ENDED = "onUserCallEnded"
        const val ON_REAL_TIME_NOTIFICATION_CONNECTED = "onRealTimeNotificationConnected"
        const val ON_CHAT_MESSAGE_RECEIVED = "onChatMessageReceived"
        const val ON_TYPING_INDICATOR_RECEIVED = "onTypingIndicatorReceived"
        const val ON_READ_RECEIPT_RECEIVED = "onReadReceiptReceived"
        const val ON_CHAT_MESSAGE_EDITED = "onChatMessageEdited"
        const val ON_CHAT_MESSAGE_DELETED = "onChatMessageDeleted"
        const val ON_CHAT_THREAD_CREATED = "onChatThreadCreated"
        const val ON_CHAT_THREAD_PROPERTIES_UPDATED = "onChatThreadPropertiesUpdated"
        const val ON_CHAT_THREAD_DELETED = "onChatThreadDeleted"
        const val ON_PARTICIPANTS_ADDED = "onParticipantsAdded"
        const val ON_PARTICIPANTS_REMOVED = "onParticipantsRemoved"
        const val ON_CHAT_PUSH_NOTIFICATION_OPENED = "onChatPushNotificationOpened"
    }

    object Prefs {
        const val PREFS_NAME = "user_data_prefs"
        const val USER_DATA_KEY = "user_data"
        const val CHAT_ENDPOINT = "chat_endpoint"
    }

    object Arguments {
        const val TOKEN = "token"
        const val NAME = "name"
        const val USER_ID = "userId"
        const val ROOM_ID = "roomId"
        const val IS_CHAT_ENABLED = "isChatEnable"
        const val IS_REJOINED = "isRejoin"
        const val ENDPOINT = "endpoint"
        const val THREAD_ID = "threadId"
        const val CONTENT = "content"
        const val SENDER_DISPLAY_NAME = "senderDisplayName"
        const val TYPE = "type"
        const val METADATA = "metadata"
        const val MESSAGE_ID = "messageId"
        const val CALL_ID = "callId"
        const val WHITEBOARD_ID = "whiteboardId"
    }

    object JsonKeys {
        const val ID = "id"
        const val INITIATOR = "initiator"
        const val THREAD_ID = "threadId"
        const val SENDER = "sender"
        const val RECIPIENT = "recipient"
        const val VERSION = "version"
        const val TYPE = "type"
        const val CREATED_ON = "createdOn"
        const val SENDER_DISPLAY_NAME = "senderDisplayName"
        const val MESSAGE = "message"
        const val METADATA = "metadata"
        const val TOPIC = "topic"
        const val CREATED_BY = "createdBy"
        const val RAW_ID = "rawId"
        const val KIND = "kind"
        const val RECEIVED_ON = "receivedOn"
        const val READ_ON = "readOn"
        const val CHAT_MESSAGE_ID = "chatMessageId"
        const val EDITED_ON = "editedOn"
        const val DELETED_ON = "deletedOn"
        const val PROPERTIES = "properties"
        const val PARTICIPANTS = "participants"
        const val UPDATED_ON = "updatedOn"
        const val UPDATED_BY = "updatedBy"
        const val DELETED_BY = "deletedBy"
        const val PARTICIPANTS_REMOVED = "participantsRemoved"
        const val REMOVED_ON = "removedOn"
        const val REMOVED_BY = "removedBy"
        const val PARTICIPANTS_ADDED = "participantsAdded"
        const val ADDED_ON = "addedOn"
        const val ADDED_BY = "addedBy"
        const val DISPLAY_NAME = "displayName"
        const val SHARE_HISTORY_TIME = "shareHistoryTime"
        const val CONTENT = "content"
    }
}